### ISSUE TITLE
Outdated cabal documentation

### ISSUE THREAD

**Issue by tomjaguarpaw** [tomjaguarpaw/tilapia#44]
> Several of the links on this page https://www.haskell.org/cabal/  are dead
https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/
or refer to old versions:
https://wiki.haskell.org/Upgrading_packages

https://mail.haskell.org/pipermail/haskell-cafe/2020-December/133139.html

**Comment by tomjaguarpaw** [comment]
Outdated or dead links on The Haskell Cabal outdated links

* "ghcup" links to https://github.com/haskell/ghcup but should be https://github.com/haskell/ghcup
* "The GHC download docs" refers to https://www.haskell.org/ghc/download_ghc_8_4_4.html. Should probably be an evergreen link.
* "How to install a cabal package" links to https://wiki.haskell.org/Cabal/How_to_install_a_Cabal_package which is outdated. This link should probably be omitted.
* "FAQ and trouble shooting" links to https://www.haskell.org/cabal/FAQ.html which is [severely outdated](https://github.com/tomjaguarpaw/tilapia/issues/47)
* "Cabal-the-library API documentation" 404s https://www.haskell.org/cabal/release/cabal-latest/doc/API/Cabal/
* "Updating packages to work with recent Cabal and GHC versions" links to https://wiki.haskell.org/Upgrading_packages and is pretty outdated
* "Old stuff" links to https://www.haskell.org/cabal/old.html. Why? Just remove it.
* "Applications and libraries" links to https://wiki.haskell.org/Applications_and_libraries which is verging on unmaintained

**Comment by tomjaguarpaw** [comment]
https://github.com/tomjaguarpaw/tilapia/issues/47 addresses the FAQ specifically

**Comment by tomjaguarpaw** [comment]
Addressing this requires knowing [who the owner of the cabal/ subsite is](https://github.com/tomjaguarpaw/tilapia/issues/46).

**Comment by lspitzner** [comment]
I'd like to add regarding https://cabal.readthedocs.io:

- that the default version of  is 3.4, which is not released. Sphinx etc. should have a concept of pre-release versions (right?)
- It calls itself the "Cabal User Guide", but we do have a) Cabal the library b) cabal-install c) cabal-the-specification. What is the user guide about? It seems at least b) and c). I think this should be mentioned at the front, and then the rest should be structured accordingly: So that the information about any `cabal-install` usage is in a separate chapter. (Note that yes, there is a `cabal-install` chapter, but there also is a `cabal.project` chapter which arguably is a feature of `cabal-install`. Also note that the very first chapter is only/at most interesting to users of cabal-install.)
- And a changelog included in the documentation would be neat.

**I will refer to the 3.4 chapter structure here**

- The introduction is the second chapter (?) It seems like you are supposed to run your first `cabal init` before you know what `cabal` is.
- chapter 4.1 is another quickstart (?)
- chapter 12.2 (interface stability) seems like a complete mess. And does not discuss the bit most important to end-users: The stability of the cabal-install commandline. Which was broken horribly in the 3.0 transition, just saying.

Or in general: The default experience you get when navigating to `https://cabal.readthedocs.io` is kind of a mess, even if it is not as outdated as the Haskell.org versions..

**Comment by tomjaguarpaw** [comment]
Thanks Lennart, those observations are really useful. I've created a new issue for them: https://github.com/tomjaguarpaw/tilapia/issues/61

**Comment by tomjaguarpaw** [comment]
Most of these have been fixed. The one that hasn't been fixed has been given its own issue: https://github.com/tomjaguarpaw/tilapia/issues/106
